sonar.host.url=https://sonarcloud.io/project/information?id=Gousa78_cyclomatic-cfg-demo
sonar.projectKey=Gousa78_cyclomatic-cfg-demo
sonar.projectName=Gousa78_cyclomatic-cfg-demo
sonar.projectOrganization=gousa78
sonar.token=sqp_72c2ef8c1dae0e070a1603843e1dd29ed90e5df2
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.test.js/,**/output/code-coverage/**,**/*.xml
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js
sonar.testExecutionReportPaths=test-report.xml
sonar.javascript.lcov.reportPaths=./output/code-coverage/lcov.info