name: CI/CD - Cyclomatic + CFG

on:
  push:
    branches: [main]

permissions:
  contents: write   # 🔥 IMPORTANT

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run analysis script
        run: node index.js

      - name: Run tests with coverage
        run: npm run test:coverage
        
      - name: Show coverage summary
        run: cat coverage/lcov-report/index.html || true

      - name: Extract coverage %
        id: coverage
        run: COVERAGE=$(node -e "; const fs=require('fs'); const data=fs.readFileSync('./coverage/coverage-summary.json'); const json=JSON.parse(data); console.log(json.total.lines.pct); ") &&         echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Save coverage JSON
        run: node -e "const fs=require('fs'); const json=JSON.parse(fs.readFileSync('./coverage/coverage-summary.json')); const pct=json.total.lines.pct; let color='red'; if(pct>=80) color='green'; else if(pct>=50) color='orange'; fs.writeFileSync('./coverage.json', JSON.stringify({schemaVersion:1,label:'coverage',message:pct+'%',color:color}));"

      - name: Update coverage badge in README
        run: 
          COVERAGE=${{ steps.coverage.outputs.coverage }}; sed -i "s|\!\[Coverage\](https://img.shields.io/badge/coverage-.*%-green)|![Coverage](https://img.shields.io/badge/coverage-${COVERAGE}%25-green)|" README.md

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@d30f5ceca2232d272f2914afec6441bc212191161
        with:
          args: >
              -Dsonar.projectKey=Gousa78_cyclomatic-cfg-demo
              -Dsonar.organization=gousa78
              -Dsonar.sources=.
              -Dsonar.branch=main
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
              
      - name: Wait for SonarCloud Quality Gate
            uses: SonarSource/sonarcloud-github-action@30f5ceca2232d272f2914afec6441bc212191161
        with:
            args: >
              -Dsonar.projectKey=Gousa78_cyclomatic-cfg-demo
              -Dsonar.organization=gousa78
              -Dsonar.branch=main 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Deploy SVGs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          commit_message: "Update CFG SVGs"